apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../compose/docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-2
  name: grafana-2
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: grafana-2
status:
  loadBalancer: {}
