apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../compose/docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "8404"
      port: 8404
      targetPort: 8404
  selector:
    io.kompose.service: haproxy
status:
  loadBalancer: {}
