apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../compose/docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter-2
  name: node-exporter-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-exporter-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../compose/docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: node-exporter-2
    spec:
      containers:
        - image: prom/node-exporter:latest
          name: node-exporter-2
          ports:
            - containerPort: 9100
          resources: {}
      restartPolicy: Always
status: {}
