apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../compose/docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter-2
  name: node-exporter-2
spec:
  ports:
    - name: "9100"
      port: 9100
      targetPort: 9100
  selector:
    io.kompose.service: node-exporter-2
status:
  loadBalancer: {}
