apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../compose/docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sqlite3
  name: sqlite3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlite3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../compose/docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: sqlite3
    spec:
      containers:
        - image: nouchka/sqlite3:latest
          name: sqlite3
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /root/db/
              name: sqlite3-claim0
      restartPolicy: Always
      volumes:
        - name: sqlite3-claim0
          persistentVolumeClaim:
            claimName: sqlite3-claim0
status: {}
